Unmatched `.
Traceback (most recent call last):
  File "/home/surface3/dgoll/SPINUP_ML/20220719/SPINacc/main.py", line 67, in <module>
    np.save(resultpath+'packdata.npy',packdata)
  File "<__array_function__ internals>", line 5, in save
  File "/usr/local/install/python-3.9/lib/python3.9/site-packages/numpy/lib/npyio.py", line 524, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/surface3/dgoll/SPINUP_ML/EXECUTION/202207CNP2/packdata.npy'
